
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class loginMenuPage extends javax.swing.JFrame {

    /**
     * Creates new form loginMenuPage
     */
    public loginMenuPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Student = new javax.swing.JButton();
        jButton_staff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000000000, 3000000));
        getContentPane().setLayout(null);

        jButton_Student.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Student.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Student.setText("I AM A STUDENT");
        jButton_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StudentActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Student);
        jButton_Student.setBounds(530, 270, 352, 51);

        jButton_staff.setBackground(new java.awt.Color(255, 255, 255));
        jButton_staff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_staff.setText("I AM A STAFF MEMBER");
        jButton_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_staffActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_staff);
        jButton_staff.setBounds(530, 390, 352, 51);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\sims\\bgimg.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100000, 30000));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1580, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StudentActionPerformed
        StudentLoginPage st=new StudentLoginPage();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_StudentActionPerformed

    private void jButton_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_staffActionPerformed
        DepLogin dl=new DepLogin();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_staffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginMenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Student;
    private javax.swing.JButton jButton_staff;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
