
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class StudentLoginPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentLoginPage
     */
    public StudentLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_studUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField_studPasswd = new javax.swing.JPasswordField();
        jButton_studentLogin = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel2.setText("USERNAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(145, 114, 100, 20);

        jTextField_studUsername.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField_studUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_studUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_studUsername);
        jTextField_studUsername.setBounds(145, 137, 211, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("PASSWORD :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(145, 176, 118, 20);

        jPasswordField_studPasswd.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jPanel1.add(jPasswordField_studPasswd);
        jPasswordField_studPasswd.setBounds(145, 199, 211, 30);

        jButton_studentLogin.setBackground(new java.awt.Color(0, 102, 255));
        jButton_studentLogin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_studentLogin.setText("LOGIN");
        jButton_studentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_studentLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_studentLogin);
        jButton_studentLogin.setBounds(270, 260, 91, 30);

        jButton_cancel.setBackground(new java.awt.Color(255, 0, 0));
        jButton_cancel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton_cancel.setText("CANCEL");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cancel);
        jButton_cancel.setBounds(140, 260, 91, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\images\\photo-1524995997946-a1c2e315a42f.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_studUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_studUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_studUsernameActionPerformed

    private void jButton_studentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_studentLoginActionPerformed
        
        Connection con=MyConnection.getConnection();
        PreparedStatement ps;
        try {
            String user=jTextField_studUsername.getText();
            String passwd=String.valueOf(jPasswordField_studPasswd.getPassword());
            
            ps=con.prepareStatement("SELECT * FROM student WHERE usn=?");
            ps.setString(1, user);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                ps=con.prepareStatement("SELECT * FROM login WHERE username=? AND password=?");
                ps.setString(1, user);
                ps.setString(2, passwd);
                rs=ps.executeQuery();
                if(rs.next()){
                    
                    searchstudent st=new searchstudent(user);
                    st.setVisible(true);
                    this.dispose();
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "WRONG PASSWORD");
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "NOT A STUDENT");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton_studentLoginActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        loginMenuPage lp=new loginMenuPage();
        lp.setVisible(true);
        lp.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_studentLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_studPasswd;
    private javax.swing.JTextField jTextField_studUsername;
    // End of variables declaration//GEN-END:variables
}
